cors:
  originPatterns: http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/springbootdb
    username: postgresql
    password: desafio
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
spring-doc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true