version: '3'
networks:
    springboot-network:
        driver: bridge

services:
  db:
    container_name: springboot-postgres
    image: bitnami/postgresql:latest
    restart: always
    ports:
        - "5440:5432"
    environment:
      - POSTGRESQL_USERNAME=postgresql
      - POSTGRESQL_PASSWORD=desafio
      - POSTGRESQL_DATABASE=springbootdb
    networks:
      - springboot-network

  rest-springboot:
    container_name: springboot-rest
    image: springboot-rest:latest
    build: .
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springbootdb
      - SPRING_DATASOURCE_USERNAME=postgresql
      - SPRING_DATASOURCE_PASSWORD=desafio
    ports:
      - "80:80"
    networks:
      - springboot-network
    depends_on:
      - db