name: continuous-integration with GitHub Actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_EMAIL }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./Springboot-rest/springboot-rest
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ./Springboot-rest/springboot-rest
      run: docker-compose build -skipTests
    
    - name: Push to Docker Hub
      run: |
        docker tag springboot-rest:latest springboot-rest:${{ github.run_id }}
        docker push springboot-rest:${{ github.run_id }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
        aws-region: aws-region-1

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
